NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

[DOCUMENTATION]
ORG_DBA="Bondao"
ORG_NAME="Bondao"
ORG_URL="https://bondaoexchange.com"
ORG_LOGO="https://bondaoexchange.com/logo.png"

[[CURRENCIES]]
code="Bondao"
issuer="GDY2VNJZYVL2BIIIPBNSSG6TOYEK5DPRN7JDXWXIGJ3N55B6QPSTEJVF"
display_decimals=7
name="Bondao"
image="https://bondaoexchange.com/logo.png"
status="live"
fixed_number=27551631842 
desc="Bondao - The Ultimate Bondao, is the fastest Bondao version ever created in the crypto space. Bondao uses the superior attributes of the Stellar blockchain. $Bondao is secure, scalable and very cheap to use."
conditions="There will only ever be 27,551,631,842 Bondao tokens in existence."